from sqlite3 import *
conn = connect("StudentManagement.db")
cur = conn.cursor()
cur.execute('insert into student values(1, "Aarav", "BCA", "FY")')
cur.execute('insert into student values(2, "Riya", "BSc CS", "SY")')
cur.execute('insert into student values(3, "Kunal", "BCA", "TY")')
cur.execute('insert into student values(4, "Meera", "BSc IT", "FY")')
cur.execute('insert into student values(5, "Rohan", "BSc CS", "TY")')
cur.execute('insert into student values(6, "Sneha", "BCA", "SY")')
cur.execute('insert into student values(7, "Tanvi", "BSc IT", "TY")')
cur.execute('insert into student values(8, "Vikram", "BSc CS", "FY")')
cur.execute('insert into student values(9, "Ankit", "BCA", "TY")')
cur.execute('insert into student values(10, "Pooja", "BSc IT", "SY")')
print("Student data inserted successfully")
conn.commit()
conn.close()
