from tkinter import * 
from tkinter.ttk import * 

win=Tk() 
win.title("Ekta Buneti - F077") 
win.geometry("500x500") 

lbl = Label(win,text="Select your Name:") 
lbl.grid() 
combo = Combobox(win) 
combo["values"]=("A","B","C","D","E") 
combo.current(2) 
combo.grid() 

lbl1 = Label(win,text="Select your Roll No.:") 
lbl1.grid(column=10,row=5) 
combo1 = Combobox(win) 
combo1["values"]=(1,2,3,4,5,6,7) 
combo1.grid(column=10,row=6) 

lbl2 = Label(win,text="Select your Class:") 
lbl2.grid(column=15,row=10) 
combo2 = Combobox(win) 
combo2["values"]=("FYCS","FYIT","SYIT","SYCS","TYIT","TYCS") 
combo2.grid(column=15,row=11) 
chk = BooleanVar() 
chk.set(True) 
chk1 = BooleanVar() 
chk1.set(False) 
chk2 = BooleanVar() 
chk2.set(False) 
chk3 = BooleanVar() 
chk3.set(False) 
lbl3 = Label(win,text="Select your Subjects:") 
lbl3.grid() 
cbtn = Checkbutton(win,text="Web Technology",var=chk) 
cbtn.grid() 
cbtn = Checkbutton(win,text="Content writing",var=chk1) 
cbtn.grid() 
cbtn = Checkbutton(win,text="OOP's",var=chk2) 
cbtn.grid() 
cbtn = Checkbutton(win,text="Python",var=chk3) 
cbtn.grid() 
chk4 = BooleanVar() 
chk4.set(False) 
chk5 = BooleanVar() 
chk5.set(True) 
chk6 = BooleanVar() 
chk6.set(False) 
chk7 = BooleanVar() 
chk7.set(False) 
lbl4 = Label(win,text="Select your City:") 
lbl4.grid() 
cbtn1 = Checkbutton(win,text="Pune",var=chk4) 
cbtn1.grid() 
cbtn1 = Checkbutton(win,text="Mumbai",var=chk5) 
cbtn1.grid() 
cbtn1 = Checkbutton(win,text="Delhi",var=chk6) 
cbtn1.grid() 
cbtn1 = Checkbutton(win,text="Kollkata",var=chk7) 
cbtn1.grid() 
win.mainloop()
